sonar.projectKey=AiOpsTask
sonar.projectName=github_task_monorepo
sonar.sources=src
sonar.tests=src/backend
sonar.test.inclusions=src/backend/**/*.test.js
sonar.exclusions=**/node_modules/**
sonar.sourceEncoding=UTF-8
